replicaCount: 3

airplane:
  apiToken: ""
  teamID: ""

  agentLabels: {}
  parallelism: 10
  runNamespace: default

  apiHost: https://api.airplane.dev
  mtaAgent: false
  runtimeClass: ""
  serviceJWTSecret: ""

image:
  repository: airplanedev/agent
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

rbac:
  create: true

serviceAccount:
  create: true
  annotations: {}

podSecurityContext: {}

securityContext: {}

nodeSelector: {}

tolerations: []

affinity: {}

sentry:
  dsn: ""
  environment: ""
