replicaCount: 3

airplane:
  # Specify either apiToken or apiTokenSecret, not both
  apiToken: ""
  apiTokenSecret:
    name: ""
    key: ""
  teamID: ""

  agentLabels: {}
  parallelism: 10
  runNamespace: default

  apiHost: https://api.airplane.dev
  mtaAgent: false
  runtimeClass: ""
  serviceJWTSecret:
    name: ""
    key: ""
  autoUpgrade: true

image:
  repository: us-docker.pkg.dev/airplane-prod/public/agent
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

rbac:
  create: true

serviceAccount:
  create: true
  annotations: {}

podSecurityContext: {}

securityContext: {}

nodeSelector: {}

tolerations: []

affinity: {}

extraLabels: {}

sentry:
  dsn: ""
  environment: ""
