replicaCount: 3

airplane:
  # Specify either apiToken or apiTokenSecret, not both
  apiToken: ""
  apiTokenSecret:
    name: ""
    key: ""
  teamID: ""

  agentLabels: {}
  runNamespace: default
  envSlug: ""

  apiHost: https://api.airplane.dev
  temporalHost: temporal-api.airplane.dev:443
  mtaAgent: false
  runtimeClass: ""
  # Node selectors to use when scheduling runs.
  # Accepts a map of key-value pairs where keys are node labels and values
  # are the expected value for that label. For example:
  # - my_node_label: my_expected_label_value
  nodeSelector: {}
  # Tolerations to use when scheduling runs. Each toleration will have an operator
  # of "Equal" and an effect of "NoSchedule".
  # Accepts a map of key-value pairs. For example:
  # - my_toleration_key: my_toleration_value
  tolerations: {}
  clusterFirstDNS: false
  serviceJWTSecret:
    name: ""
    key: ""
  autoUpgrade: true

image:
  repository: us-docker.pkg.dev/airplane-prod/public/agentv2
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

rbac:
  create: true

serviceAccount:
  create: true
  annotations: {}

podSecurityContext: {}

securityContext: {}

# Node selectors to use when scheduling agents.
# Accepts a map of key-value pairs where keys are node labels and values
# are the expected value for that label. For example:
# - my_node_label: my_expected_label_value
nodeSelector: {}

# Tolerations to use when scheduling agents.
# Accepts a list of tolerations. For example:
# - key: "my_toleration_key"
#   operator: "Equal"
#   value: "my_toleration_value"
#   effect: "NoSchedule"
tolerations: []

affinity: {}

extraLabels: {}

sentry:
  dsn: ""
  environment: ""
