{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Values.airplane.runNamespace }}
  name: {{ include "kubernetes_agent.fullname" . }}
  labels: {{- include "kubernetes_agent.labels" . | nindent 4 }}
rules:
  - apiGroups: ["apps"]
    resources: ["replicasets"]
    verbs: ["get", "create", "list", "delete", "update"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "patch", "delete"]
{{- end -}}
