{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Values.airplane.runNamespace }}
  name: {{ include "kubernetes_agent.fullname" . }}
  labels: {{- include "kubernetes_agent.labels" . | nindent 4 }}
rules:
  - apiGroups: ["apps"]
    resources: ["replicasets"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: [""]
    resources: ["pods", "secrets"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["", "events.k8s.io"]
    resources: ["events"]
    verbs: ["get", "list", "watch"]
{{- end -}}
