name: Lint

on:
  push:
    branches: ["main"]
  pull_request: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.12.1

      - name: Run lint
        run: |
          helm lint --quiet \
            ./airplane-agent \
            --namespace=helm-test \
            --set image.repository=kind-agent \
            --set image.pullPolicy=Never \
            --set airplane.apiHost="http://host.docker.internal:8080" \
            --set airplane.apiToken=tkn_gIUh8Yay7MVKH4A5TpvsjhdixGVTKIKe4hTF \
            --set airplane.teamID=1jq9NDeTcTmyqqXAjEsk7V0wXaV \
            --set airplane.envSlug=prod \
            --set airplane.debugMode=true \
            --set airplane.useECRPublicImages=false \
            --set airplane.extraEnvVars.KEY1=VALUE1 \
            --set airplane.extraEnvVars.KEY2=VALUE2 \
            --set airplane.extraEnvVars.KEY3='{"key1": "value1"}' \
            --set airplane.storage.enabled=true \
            --set airplane.taskPodSecurityContext.key=value \
            --set airplane.taskSecurityContext.key=value \
            --set airplane.agentLabels.key1=value1 \
            --set tolerations[0].key=my_toleration_key \
            --set tolerations[0].operator=Equal \
            --set tolerations[0].value=my_toleration_value
